### ISSUE TITLE
Home Page Code School Q&A Description

### ISSUE THREAD

**Issue by carmenkolohe** [carmenkolohe/CodeSchoolQA#10]
Currently the splash page is a brief paragraph, an input box for questions to be submitted to the database and a list of questions if there are any in the database. It would be nice to have something friendly to welcome users.

**Comment by emmalearnscode** [comment]
Do you have something firendly in mind or do you mean you want the design/layout changing to look more friendly? Do you want a design submitted first so that changes can be made later or is it ok to go ahead an make changes directly? and do you already have a theme to work from (I don't see a link to the hosted site anywhere so I don't know how the site currently looks).

**Comment by jendevelops** [comment]
> Do you have something firendly in mind or do you mean you want the design/layout changing to look more friendly? Do you want a design submitted first so that changes can be made later or is it ok to go ahead an make changes directly? and do you already have a theme to work from (I don't see a link to the hosted site anywhere so I don't know how the site currently looks).

@emmalearnscode thanks for asking a bunch of excellent clarifying questions! We are still in the process of writing the tickets for this repository, so please feel free to check back in later tonight/ tomorrow (October 1st) for new, more explicit tickets up for grabs. Thanks again!
